### ISSUE TITLE
AmMaps

### ISSUE THREAD

**Issue by smuller20** [ChimpStudios/AmCharts#10]
Love AmCharts, AmMaps, it is a huge part of our web data display. I understand the js version but I am really struggling with the wrapper classes. Currently working on an iPad app,  I have pie charts, barcharts all working fine. I can't seem to find an example of the wrapper classes for amMaps and its killing me. Could you point me to a simple snippet of how to set up the map? Thank you.

**Comment by AndrewSchenk** [comment]
@smuller20 take a look at the updated ReadMe.  https://github.com/chimpstudios/amcharts#world-map

You were probably just missing the chart.html template file that needs to have the proper maps added in the header section.  You can use:
```
setTemplateFilepath:
```
to use your own cloned chart.html and resources.  That way, your changes don't conflict with the master branch.

**Comment by smuller20** [comment]
Thanks for your quick response. You were spot on with what I had overlooked. Thank you!!
