### ISSUE TITLE
clickMapObject 

### ISSUE THREAD

**Issue by smuller20** [ChimpStudios/AmCharts#11]
Me again. I have been struggling with how to determine which country was selected in the map. I create an array of countries which I use to populate other charts data. 
In my website .js version I do this:

var arrCountry = [];

 map.addListener('clickMapObject', function (event) {
        arrCountry = [];
        var selectedCountry = event.mapObject.id;
        arrCountry.push(selectedCountry);
}

I don't know how to reference 'clickMapObject' for iOS.

Also, I can't figure out what to call when I 'manually' want to select a country. (A search result will return a country that I use to select in map)

My code is Swift - I am happy to have any help in Objective-c and I can just translate

var countryArray = ["US"];
for sArea in map.mapDataProvider.areas as NSArray as [AmMapArea]{
    var areaID = sArea.uid;
    if contains(countryArray, areaID!){
      sArea.showAsSelected = true; // highlights
      // How to zoom here? ( I am using an array but in this case it will always only have one country)
    }else{
       sArea.showAsSelected = false;
   }

Thank you

**Comment by AndrewSchenk** [comment]
Please ask questions about personal projects on StackOverflow.  This space is reserved for bugs with the AmCharts wrapper library.
