### ISSUE TITLE
Creating XYChart

### ISSUE THREAD

**Issue by donaldkingdt** [ChimpStudios/AmCharts#15]
Hi,

Could you point to documentation on how to create this chart in objective c: 
http://www.amcharts.com/demos/multiple-value-axes/#theme-light

Cheers

**Comment by AndrewSchenk** [comment]
Go to that URL.  Click on the "Edit" button.  Now you can see the JSON configuration that they used to make the chart.  Duplicate it using AmChart objects from this library.

````
AmValueAxis *valAxis1 = [[AmValueAxis alloc] init];
valAxis1.id = "v1";
// etc etc
chart.valueAxes = @[valAxis1, valAxis2, valAxis3];
````
