### ISSUE TITLE
"AmChartsMobile/AmCharts.h' file not found" when running Archive

### ISSUE THREAD

**Issue by MickeDG** [ChimpStudios/AmCharts#4]
Hi again!

I get <b>'AmChartsMobile/AmCharts.h' file not found</b> when I run Archive for my project. Works fine when running on the phone and in the simulator...

Best regards,
Mikael DG

I think I found it . had forgotten about -ObjC for other configurations. I had put it i DEBUG but not the others...ADHOC and RELEASE...

**Comment by hogwild** [comment]
Hi, I got the same issue, could you tell how to make the settings? Thank you very much.
