### ISSUE TITLE
There is only one view can be drawn?

### ISSUE THREAD

**Issue by linkeo** [ChimpStudios/AmCharts#8]
In OS X Application, I use 3 AmChartView in single window, but only **one** AmChartView works.

All the way, I just want to display several charts in single window.

(A Swift Cocoa Application on OS X, Xcode 6.2 Beta 3)

**Comment by AndrewSchenk** [comment]
![multiple charts](https://cloud.githubusercontent.com/assets/625821/5681532/dfa6ce80-97de-11e4-911a-24cea64c5fff.png)

There seems to be some sort of problem with multiple charts.  For some reason the frame load delegate method is not being called in AmChartView for N+1 charts.  A quick fix for this is to force the setup method again in AmChartView.  This can be done with a call to 
```
setTemplateFilepath:
```
For example:
```
[self.chartView2 setTemplateFilepath:[[NSBundle bundleWithIdentifier:@"com.chimpstudios.AmCharts"] pathForResource:@"chart" ofType:@"html" inDirectory:@"AmChartsWeb3"]];
[self.chartView2 setChart:stockChart];
    [self.chartView2 drawChart];
```

**Comment by linkeo** [comment]
Thank you, it works this way!

**Comment by arodeus** [comment]
Hello,
same problem with iOS, but setTemplateFilepath workaround is not usable becouse the method is missing in iOS version.

**Comment by linkeo** [comment]
Hello, I solved this problem in another way, it maybe useful in iOS. I copied the AmChartView class and made some change to support multi-charts in a view. 

- change property `chart` to several chart properties, and update methods which used this property.
- change method `drawChart`, send several chart object to javascript function (which I changed in html file).

I give some important code to you:

```objc
// first I copied AmChartView to my AmFFTChartView
// in AmFFTChartView.h, remove chart property and add properties
@property (strong, nonatomic) id rawchart;
@property (strong, nonatomic) id rechart;
@property (strong, nonatomic) id imchart;

// in AmFFTChartView.m : -(void) drawChart
NSString *scrpt = [NSString stringWithFormat:@"generateFFTChartWithJSONData(%@);",
                    [NSString stringWithFormat:@"{raw:%@,re:%@,im:%@}",
                      [_rawchart javascriptRepresentation],
                      [_rechart javascriptRepresentation],
                      [_imchart javascriptRepresentation]
                    ]
                  ];
NSLog(@"Evaluate %@",scrpt);
[_context evaluateScript:scrpt];
//...

// add setters for these properties, add update validateChart to invalidate sizes of these charts.
```

HTML:

I copied chart.html to fftchart.html ,add made some change:

``` js
// change function to generateFFTChartWithJSONData(json):

// in that script tag

var rawchart,rechart,imchart;

function generateFFTChartWithJSONData(json) {
    rawchart = AmCharts.makeChart("rawchartdiv", json.raw);
    rechart = AmCharts.makeChart("rechartdiv", json.re);
    imchart = AmCharts.makeChart("imchartdiv", json.im);
}
```

and change html document & css to layout those charts.

**Comment by arodeus** [comment]
@linkeo , thanks for the code... I'll try this ASAP.

Diego

**Comment by linkeo** [comment]
BTW, this solution is suitable for fixed count and layout of chart.

You can operate DOM in method `drawChart` to get more flexibility, however, with longer code...

**Comment by AndrewSchenk** [comment]
linkeo's code works for a very specific use-case, exactly 3 charts in a single web view.  If you are dynamically adding or removing charts at runtime this will not work correctly.

**Comment by arodeus** [comment]
I'm adding one single chart per collection view cell.

**Comment by linkeo** [comment]
@AndrewSchenk 
Exactly. I just made change to meet my requirement in a single project - to show FFT. I didn't think of more flexibility. However, it seems to be a general requirement to display multiple charts in a time.

**Comment by AndrewSchenk** [comment]
@arodeus try the latest commit.  It adds initWithCoder: and setTemplateFilepath: 

https://github.com/ChimpStudios/AmCharts/commit/a51cf6053e04464dc9e5a6a249ba0bad0b24d483

**Comment by arodeus** [comment]
@AndrewSchenk thanks!

**Comment by AndrewSchenk** [comment]
I figured out the multiple charts on a page not drawing issue.  Instead of using

```
loadRequest:
```
web views need to use
```
loadHTMLString:baseURL:
```

![screen shot 2015-01-20 at 10 15 53 am](https://cloud.githubusercontent.com/assets/625821/5820878/aafde436-a08d-11e4-8b91-e2b02996d3b0.png)

I will commit the fixes shortly.

**Comment by arodeus** [comment]
@AndrewSchenk great! That's exactly what I'm going to develop! ^_^

**Comment by arodeus** [comment]
@AndrewSchenk , sorry for dumb question: I updated the project but XCode seems compiling using the previous .a file. Any idea?

**Comment by AndrewSchenk** [comment]
clean all the targets, and delete the derived data for the project in Window > Organizer > Projects

**Comment by arodeus** [comment]
perfect thanks! ^_^ I'm still not able to load all the graphs as your screenshot, but probably now it's my fault.

**Comment by arodeus** [comment]
@AndrewSchenk ... ok done! Thanks for the support!

**Comment by AndrewSchenk** [comment]
@arodeus Here is the project that I took a screenshot from.
https://dl.dropboxusercontent.com/u/12790096/AmCharts/AmCharts.zip

**Comment by arodeus** [comment]
@AndrewSchenk , you're very kind. Meanwhile I solved my problem: it was a stupid constraints-related problem.
